trigger:
- master

variables:
  python_version: '3.8.1'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: PythonBuildAndTest
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'Open FTTH package compile and test'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(python_version)
      displayName: 'Use Python version $(python_version)'
    - script: python -m pip install --upgrade pip
      displayName: 'Install pip'

    - script: |
        pip install pb_tool pyqt5
      displayName: 'Install plugin dependencies'

    - script: |
        pip install nose nosetests-json-extended coverage
      displayName: 'Install testing dependencies'

    - script: |
        sudo apt-get install qgis
        sudo apt-get install python3-pyqt5 
      displayName: 'Install QGIS dependencies'

    - script: |
        source ./scripts/run-env-linux.sh /usr/share/qgis
      displayName: 'Source run-env-linx script enable testing'
    
    - script: pb_tool compile
      displayName: 'Compile with pb_tool'
    
    - script: make test
      displayName: 'Run tests'
